version: '3.8'

services: 
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riderize
    ports: 
      - 5432:5432
    volumes: 
      - riderize:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes: 
  riderize: